### ISSUE TITLE
template 'application' not ready at the time of initialize() firefox.

### ISSUE THREAD

**Issue by sabithpocker** [ghempton/ember-router-example#1]
I was not able to make this work in firefox,  waiting for onload for calling initialize made it work

$(function() {
App.initialize();
});

I am not aware of the actual problem, looks like the 'application' template is not yet ready by then.

Discussion here helped me with this quick fix http://stackoverflow.com/questions/9222537/why-does-this-ember-js-app-fail-in-firefox

Any idea what is causing this?

**Comment by ghempton** [comment]
Seems vaguely familiar. Looks like something internal to Ember which parses inline handlebars templates behaves differently on firefox. I think your fix is the correct workaround. Care to make a PR?

**Comment by ghempton** [comment]
Fixed by #2
